# Generated by Django 3.1.12 on 2025-09-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacaoJEBR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_importacao', models.DateTimeField(auto_now_add=True)),
                ('arquivo_fonte', models.CharField(help_text='Nome do arquivo Excel importado', max_length=500)),
                ('url_fonte', models.URLField(blank=True, default='https://gilbertomelo.com.br/fam/jebr_n_xls.php', null=True)),
                ('registros_processados', models.PositiveIntegerField(default=0)),
                ('registros_criados', models.PositiveIntegerField(default=0)),
                ('registros_atualizados', models.PositiveIntegerField(default=0)),
                ('registros_erro', models.PositiveIntegerField(default=0)),
                ('registros_ignorados', models.PositiveIntegerField(default=0)),
                ('data_inicial_importada', models.DateField(blank=True, null=True)),
                ('data_final_importada', models.DateField(blank=True, null=True)),
                ('sucesso', models.BooleanField(default=False)),
                ('mensagem_erro', models.TextField(blank=True, null=True)),
                ('tempo_execucao', models.DurationField(blank=True, null=True)),
                ('detalhes_importacao', models.JSONField(blank=True, help_text='Detalhes técnicos da importação', null=True)),
            ],
            options={
                'verbose_name': 'Importação JEBR',
                'verbose_name_plural': 'Importações JEBR',
                'db_table': 'importacao_jebr',
                'ordering': ['-data_importacao'],
            },
        ),
        migrations.CreateModel(
            name='IndiceJEBR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_referencia', models.DateField(help_text='Data de referência do índice JEBR', unique=True)),
                ('valor_indice', models.DecimalField(decimal_places=10, help_text='Valor do índice JEBR com alta precisão', max_digits=20)),
                ('variacao_mensal', models.DecimalField(blank=True, decimal_places=6, help_text='Variação percentual em relação ao mês anterior', max_digits=10, null=True)),
                ('variacao_anual', models.DecimalField(blank=True, decimal_places=6, help_text='Variação percentual em relação ao mesmo mês do ano anterior', max_digits=10, null=True)),
                ('fator_acumulado', models.DecimalField(blank=True, decimal_places=10, help_text='Fator acumulado desde a data base (útil para cálculos)', max_digits=20, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('data_importacao', models.DateTimeField(blank=True, help_text='Data da última importação deste registro', null=True)),
                ('ativo', models.BooleanField(default=True, help_text='Registro ativo')),
                ('oficial', models.BooleanField(default=True, help_text='Se é um valor oficial (True) ou estimado (False)')),
            ],
            options={
                'verbose_name': 'Índice JEBR',
                'verbose_name_plural': 'Índices JEBR',
                'db_table': 'indice_jebr',
                'ordering': ['-data_referencia'],
            },
        ),
        migrations.AddIndex(
            model_name='indicejebr',
            index=models.Index(fields=['data_referencia'], name='indice_jebr_data_re_2bf33e_idx'),
        ),
        migrations.AddIndex(
            model_name='indicejebr',
            index=models.Index(fields=['-data_referencia'], name='indice_jebr_data_re_dfc9f1_idx'),
        ),
        migrations.AddIndex(
            model_name='indicejebr',
            index=models.Index(fields=['data_importacao'], name='indice_jebr_data_im_8d9cb9_idx'),
        ),
    ]
